[package]
name = "mq"
version = "0.1.0"
edition = "2021"
[dependencies]
minicbor = { version = "0.20.0", features = ["derive"] }

[[bin]]
name = "mq"
path = "src/bin/mq/main.rs"
[[bin]]
name = "publish"
path = "src/bin/publish/main.rs"
